yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))

]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
TEXT_LEN: int = 15


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Ссылка')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:TEXT_LEN]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Комментарий',
        help_text='Комментарий к посту'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:TEXT_LEN]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Вы обязательно должны ввести текст!')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Вы обязательно должны ввести текст!')
        return data

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, User
from .utils import paginator_create


def index(request):
    post_list = Post.objects.all()
    page_obj = paginator_create(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator_create(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator_create(request, post_list)
    post_count = post_list.count()
    context = {
        'author': author,
        'post_count': post_count,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_more = get_object_or_404(Post, pk=post_id)
    post_count = post_more.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = post_more.comments.all()
    context = {
        'post_more': post_more,
        'post_count': post_count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/post_create.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if request.method == "POST":
        if form.is_valid:
            form.save()
            return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True, 'post': post}
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>   
    {% for post in page_obj %}
      {% include "posts/includes/post_card.html" %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <h1>Последние обновления на сайте</h1>  
      {% for post in page_obj %}
        {% include "posts/includes/post_card.html" %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>   
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост 
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост  
          {% else %}
            Новый пост
          {% endif %} 
        </div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              

              {% if is_edit %}
                <form method="post" action="{% url 'posts:post_edit' post.pk %}" enctype="multipart/form-data">
              {% else %}
                <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
              {% endif %}
                {% csrf_token %}            
                {% for field in form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }} 
                      {% if field.help_text %}
                        <small 
                           id="{{ field.id_for_label }}-help"
                           class="form-text text-muted"
                        >
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
                </div>
            </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост   {{ post_more.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{post_more.pub_date}}
        </li>
        {% if post_more.group %}
          <li class="list-group-item">
            Группа: {{post_more.group}}
            <a href="{% url 'posts:group_list' post_more.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{post_more.author}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span> {{post_count}}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post_more.author %}">все посты пользователя </a>   
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post_more.image "960x339" crop="center" upscale=True as im %}
        <p><img class="card-img my-2" src="{{ im.url }}"></p>
      {% endthumbnail %}
      <p>
      {{post_more.text}}
      </p>
      {% if post_more.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post_more.id %}">
          редактировать запись
        </a> 
      {% endif %}
      {% include "posts/includes/comment_create.html" %}
    </article>
  </div> 
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя  {{ user.username }}{% endblock %}
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{user.username}} </h1>
  <h3>Всего постов: {{post_count}} </h3>   
  <article>
    <p>
      {% for post in page_obj %}
        {% include "posts/includes/post_card.html" %}    
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </p>
  </article>          
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}